### ISSUE TITLE
Add get_data_uri parameter to get_signature_request_file

### ISSUE THREAD

**Issue by johnnycupcakes** [hellosign/hellosign-python-sdk#52]
response = client.get_signature_request_file(
        signature_request_id='ID',
        filename='=files.pdf',
        file_type='pdf',
        get_data_uri='true'

Results in 
TypeError: get_signature_request_file() got an unexpected keyword argument 'get_data_uri'
Thank you

**Comment by Framinus** [comment]
This workaround uses the Python Requests Library:

```import requests
API_KEY = 'YOUR_API_KEY'
SIGNATURE_REQUEST_ID = 'YOUR_SIGNATURE_REQUEST_ID'
URL = 'https://'+API_KEY+':@api.hellosign.com/v3/signature_request/files/'+SIGNATURE_REQUEST_ID
PARAMS = {'get_url': True}
r = requests.get(url = URL, params = PARAMS)
data = r.json()
print(data)
```

**Comment by oconnor-sn** [comment]
I believe this issue can be closed due to Merge of #51 

@alexmac05 - can you review and confirm

**Comment by erosiec** [comment]
This will work using  Python SDK version 3.8.9 and here is the syntax:

urlResponse = client.get_signature_request_file(
signature_request_id='Signature_REQUEST_ID_HERE',
response_type='data_uri'
)
